"""init

Revision ID: 05180a9bbade
Revises: 
Create Date: 2025-01-13 05:40:15.070293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05180a9bbade'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_video_request',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('input_sample', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('narration', sa.Text(), nullable=True),
    sa.Column('output_video_url', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('process_percent', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_video_request')
    # ### end Alembic commands ###
